# Generated by Django 5.2.4 on 2025-08-14 05:46

import datetime
import django.db.models.deletion
import django.utils.timezone
import nepali_datetime_field.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCModel',
            fields=[
                ('kyc_id', models.AutoField(primary_key=True, serialize=False)),
                ('salutation', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], default='Mr', max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('nep_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('nationality', models.CharField(choices=[('Nepalese', 'Nepalese'), ('Indian', 'Indian'), ('Other', 'Other')], default='Nepalese', max_length=50)),
                ('date_of_birth_ad', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('dob_bs', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nep_father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('grand_father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('grandfather_in_law_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_in_law_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('son_name', models.CharField(blank=True, max_length=100, null=True)),
                ('daughter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('daughter_in_law_name', models.CharField(blank=True, max_length=100, null=True)),
                ('proposer_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age_proof_doc', models.CharField(choices=[('Citizenship', 'Citizenship'), ('Passport', 'Passport'), ('Birth Certificate', 'Birth Certificate'), ('Other', 'Other')], default='Citizenship', max_length=50)),
                ('document_number', models.CharField(max_length=100, verbose_name='Document Number')),
                ('document_issued_date_bs', nepali_datetime_field.models.NepaliDateField(verbose_name='Document Issued Date (B.S.)')),
                ('document_issued_date', models.DateField(verbose_name='Document Issued Date (A.D.)')),
                ('issued_place', models.CharField(blank=True, choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur')], max_length=100, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_nepali', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('temporary_address', models.CharField(blank=True, max_length=255, null=True)),
                ('temporary_district', models.CharField(blank=True, max_length=100, null=True)),
                ('ward_no', models.CharField(blank=True, max_length=10, null=True)),
                ('house_no', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('local_unit', models.CharField(choices=[('Kathmandu Metropolitan City', 'Kathmandu Metropolitan City'), ('Pokhara Metropolitan City', 'Pokhara Metropolitan City'), ('Lalitpur Metropolitan City', 'Lalitpur Metropolitan City'), ('Biratnagar Metropolitan City', 'Biratnagar Metropolitan City'), ('Bharatpur Metropolitan City', 'Bharatpur Metropolitan City'), ('Birgunj Metropolitan City', 'Birgunj Metropolitan City')], default='Municipality', max_length=50)),
                ('structure', models.CharField(choices=[('Metropolitan City', 'Metropolitan City'), ('Sub-Metropolitan City', 'Sub-Metropolitan City'), ('Municipality', 'Municipality'), ('Rural Municipality', 'Rural Municipality'), ('Ward', 'Ward')], default='Metropolitan City', max_length=50)),
                ('email', models.EmailField(blank=True, default='test@example.com', max_length=254, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('qualification', models.CharField(blank=True, choices=[('SLC', 'SLC'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Other', 'Other')], max_length=100, null=True)),
                ('profession', models.CharField(choices=[('Service', 'Service'), ('Business', 'Business'), ('Other', 'Other')], default='Service', max_length=50)),
                ('income_mode', models.CharField(choices=[('Salary', 'Salary'), ('Business', 'Business'), ('Investment', 'Investment'), ('Other', 'Other')], default='Salary', max_length=50)),
                ('income_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_ac_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_ac_no', models.CharField(blank=True, max_length=50, null=True)),
                ('office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('firm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_category', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10, verbose_name='Risk Category')),
                ('is_politically_involved', models.BooleanField(default=False)),
                ('is_aml_crime', models.BooleanField(default=False)),
                ('is_family_politically_involved', models.BooleanField(default=False)),
                ('is_family_aml_crime', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KYC Detail',
                'verbose_name_plural': 'KYC Details',
            },
        ),
        migrations.CreateModel(
            name='KYCList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_no', models.CharField(default=0, max_length=50, verbose_name='Client Number')),
                ('new_client_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='New Client Number')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('mobile_no', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('is_policy_issued', models.BooleanField(default=False, verbose_name='Policy Issued Status')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('created_by', models.ForeignKey(default=1, help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='created_kyc_records', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('kyc_detail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_list_entry', to='kyc.kycmodel')),
            ],
            options={
                'verbose_name': 'KYC List Entry',
                'verbose_name_plural': 'KYC List Entries',
            },
        ),
    ]
